// Generated by Supabase CLI
export type Json = string | number | boolean | null | { [key: string]: Json } | Json[];

export interface Database {
  public: {
    Tables: {
      bills: {
        Row: {
          id: string;
          title: string;
          total_amount: number | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          total_amount?: number | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          total_amount?: number | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "bills_created_by_fkey";
            columns: ["created_by"];
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      participants: {
        Row: {
          id: string;
          name: string;
          bill_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          bill_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          bill_id?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "participants_bill_id_fkey";
            columns: ["bill_id"];
            referencedRelation: "bills";
            referencedColumns: ["id"];
          }
        ];
      };
      items: {
        Row: {
          id: string;
          bill_id: string;
          name: string;
          cost: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          bill_id: string;
          name: string;
          cost: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          bill_id?: string;
          name?: string;
          cost?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "items_bill_id_fkey";
            columns: ["bill_id"];
            referencedRelation: "bills";
            referencedColumns: ["id"];
          }
        ];
      };
      item_assignments: {
        Row: {
          id: string;
          item_id: string;
          participant_id: string;
          share: number | null;
        };
        Insert: {
          id?: string;
          item_id: string;
          participant_id: string;
          share?: number | null;
        };
        Update: {
          id?: string;
          item_id?: string;
          participant_id?: string;
          share?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "item_assignments_item_id_fkey";
            columns: ["item_id"];
            referencedRelation: "items";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "item_assignments_participant_id_fkey";
            columns: ["participant_id"];
            referencedRelation: "participants";
            referencedColumns: ["id"];
          }
        ];
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
    CompositeTypes: {};
  };
}
